/**
 * NPC dialogue system for Towers (TD).
 *
 * "Vesk, the Hexwarden" is the player's gruff field commander. She reacts to
 * live game events with one-line barks generated by qwen2.5 through the AI
 * gateway. Design rules:
 *
 *   1. NEVER block the wave loop. Callers fire-and-forget:
 *        npc.bark(evt, ctx).then(line => io.emit('npc:say', { line }))
 *      bark() always resolves to a string (LLM result OR a fallback line),
 *      so the UI always has something to show.
 *   2. Cheap + bounded. Barks only fire on discrete events (wave start, base
 *      hit, victory...), not per-tick, so we never flood the GPU.
 *   3. Personality is server-owned. The persona prompt lives here so every
 *      map/run gets a consistent character.
 */
import { chat } from './client.js';
import { config } from '../../config/index.js';

const PERSONA = `You are Vesk, the Hexwarden - a battle-hardened commander defending a hex realm from waves of invaders in a tower-defense game.
Voice: terse, dry, war-weary but loyal to the player (the "Architect" who builds the towers).
Rules: reply with ONE short line of dialogue, max 18 words. No emojis. No quotation marks. No stage directions. Stay in character. React to the situation you are given.`;

/**
 * Fallback line banks - used when the LLM is slow, disabled, or unreachable.
 * Keeps the game feeling alive even with the gateway down.
 */
const FALLBACKS = {
  'story': [
    'Hold fast, Architect. The story is not yet written.',
    'Stand ready. What comes next is ours to decide.',
    'Eyes up. This is where legends are forged.',
  ],
  'run:start': [
    'Towers up, Architect. The hexes are yours to hold.',
    'They are coming. Build well and build fast.',
    'Another siege. Let us make the lanes run red.',
  ],
  'wave:start': [
    'Wave incoming - eyes on the spawn hex.',
    'Here they come. Hold the line.',
    'Next wave breaking. Mind your currency.',
  ],
  'wave:cleared': [
    'Wave broken. Reinforce before the next.',
    'Cleared. Spend the lull wisely, Architect.',
    'They fall back. Use the quiet.',
  ],
  'base:hit': [
    'They breached the core - patch our defenses!',
    'Base is taking damage. Plug that lane.',
    'We are bleeding at the base. Move.',
  ],
  'tower:placed': [
    'Good placement. Make it count.',
    'New emplacement online.',
    'That lane just got meaner.',
  ],
  'run:won': [
    'Realm holds. The hexes are ours - well built, Architect.',
    'Last of them down. We held.',
    'Victory. The towers sang today.',
  ],
  'run:lost': [
    'The core is gone. We rebuild and we return.',
    'Overrun. Learn the lanes and try again.',
    'They took it. Next time we hold.',
  ],
};

function fallback(evt) {
  const bank = FALLBACKS[evt] || FALLBACKS['wave:start'];
  return bank[Math.floor(Math.random() * bank.length)];
}

/**
 * Turn a game event + context into a natural-language situation for the LLM.
 */
function describe(evt, ctx = {}) {
  switch (evt) {
    case 'run:start':   return `The siege begins on the map "${ctx.mapName || 'an unknown field'}". The Architect has ${ctx.currency ?? 0} currency to build with.`;
    case 'wave:start':  return `Wave ${(ctx.wave ?? 0) + 1} is spawning with ${ctx.totalEnemies ?? 'several'} invaders.`;
    case 'wave:cleared':return `Wave ${(ctx.wave ?? 0) + 1} has been wiped out. Base health is ${ctx.baseHealth ?? 100}.`;
    case 'base:hit':    return `Enemies reached the base. Base health has dropped to ${ctx.baseHealth ?? '??'}.`;
    case 'tower:placed':return `The Architect just built a ${ctx.towerName || 'new tower'}.`;
    case 'run:won':     return `Every wave is defeated. The realm survived with ${ctx.baseHealth ?? 0} base health and a score of ${ctx.score ?? 0}.`;
    case 'run:lost':    return `The base has fallen. The invaders won. Final score was ${ctx.score ?? 0}.`;
    case 'story':       return `Speak as ${ctx.name || 'the commander'}${ctx.role ? ', ' + ctx.role : ''}. Situation: ${ctx.seed || 'address the Architect before the next wave'}. One in-character line.`;
    default:            return `Something happened: ${evt}.`;
  }
}

/**
 * Generate (or fall back to) a single NPC line for an event.
 * Always resolves to a non-empty string. Never throws.
 *
 * @param {string} evt   event key (e.g. 'wave:start')
 * @param {object} ctx   contextual data for the prompt
 * @returns {Promise<string>}
 */
export async function bark(evt, ctx = {}) {
  if (!config.ai.npcEnabled) return fallback(evt);

  const line = await chat(
    [
      { role: 'system', content: PERSONA },
      { role: 'user', content: describe(evt, ctx) },
    ],
    { temperature: 0.9, maxTokens: 48, timeoutMs: 12000 }
  ).catch(() => null);

  if (!line) return fallback(evt);

  // Sanitize: strip wrapping quotes, collapse to one line, hard length cap.
  let clean = line.replace(/^["'\s]+|["'\s]+$/g, '').split('\n')[0].trim();
  if (clean.length > 160) clean = clean.slice(0, 157).trimEnd() + '...';
  return clean || fallback(evt);
}

/**
 * Free-form chat with the commander (used by the REST endpoint / UI tavern).
 * @param {string} userText
 * @param {Array<{role,content}>} history
 */
export async function converse(userText, history = []) {
  if (!config.ai.npcEnabled) {
    return 'The commander is off the comms right now. Try again later, Architect.';
  }
  const messages = [
    { role: 'system', content: PERSONA + '\nYou may answer the Architect\'s questions about strategy, but stay terse and in character.' },
    ...history.slice(-6),
    { role: 'user', content: userText },
  ];
  const line = await chat(messages, { temperature: 0.85, maxTokens: 120, timeoutMs: 20000 });
  return line || 'Static on the line, Architect. Say again.';
}

export default { bark, converse };
