/**
 * Story — a narrative arc attached to a map. An arc is an ordered set of BEATS;
 * each beat fires on a trigger during a run (run start, a given wave starting or
 * clearing, base health crossing a threshold, an objective completing, win/lose)
 * and shows a narrative modal: a speaker (NPC) with an SD-generated headset
 * portrait, one or more dialogue lines, and optional effects.
 *
 * Authored in the Story Arc builder (beside the Map + Tower builders). The engine
 * fires beats server-side and emits `story:beat` so the client pops the modal.
 */
import mongoose from 'mongoose';

// A speaking character. portraitUrl is an SD-generated "headset" bust shot
// (generated by scripts/gen-story-art.js from the prompt, saved under
// /assets/img/story/<slug>.png). Falls back to Vesk if absent.
const characterSchema = new mongoose.Schema({
  slug: { type: String, required: true },          // e.g. 'vesk', 'scout-7'
  name: { type: String, required: true },           // display name
  role: { type: String, default: '' },              // subtitle, e.g. 'Field Commander'
  color: { type: String, default: '#33ddff' },      // accent / nameplate colour
  portraitUrl: { type: String, default: '' },        // SD headshot
  portraitPrompt: { type: String, default: '' },     // prompt the art-gen used
  persona: { type: String, default: '' },            // optional LLM persona override
}, { _id: false });

// One narrative beat.
const beatSchema = new mongoose.Schema({
  id: { type: String, required: true },              // stable id within the arc
  // trigger: when this beat fires
  trigger: {
    type: { type: String, default: 'wave-start',
      enum: ['run-start', 'wave-start', 'wave-cleared', 'base-below', 'objective-complete', 'objective-failed', 'run-won', 'run-lost', 'manual'] },
    wave: { type: Number, default: 0 },              // for wave-start / wave-cleared
    threshold: { type: Number, default: 50 },        // for base-below (% health)
    objectiveId: { type: String, default: '' },      // for objective-* triggers
    once: { type: Boolean, default: true },          // fire only the first time
  },
  speaker: { type: String, default: 'vesk' },        // character slug
  // dialogue: array of lines (the modal advances through them)
  lines: [{ type: String }],
  // optional: let the LLM improvise this beat in the speaker's persona instead of
  // using the scripted lines (lines act as a fallback / seed).
  improvise: { type: Boolean, default: false },
  // optional gameplay effects when the beat fires
  effects: {
    grantCurrency: { type: Number, default: 0 },
    healBase: { type: Number, default: 0 },
    pauseUntilDismissed: { type: Boolean, default: false },  // halt the wave loop during the modal
  },
}, { _id: false });

const storySchema = new mongoose.Schema({
  title: { type: String, required: true, trim: true, maxlength: 120 },
  slug: { type: String, required: true, unique: true, lowercase: true },
  synopsis: { type: String, maxlength: 800, default: '' },

  mapId: { type: mongoose.Schema.Types.ObjectId, ref: 'Map' },   // arc belongs to a map
  mapSlug: { type: String, default: '' },

  authorId: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  authorName: { type: String },

  characters: [characterSchema],
  beats: [beatSchema],

  status: {
    type: String,
    enum: ['draft', 'submitted', 'approved', 'rejected', 'featured'],
    default: 'draft',
  },
}, { timestamps: true });

storySchema.index({ mapId: 1, status: 1 });

export default mongoose.model('Story', storySchema);
