import mongoose from "mongoose";
import { track as trackDb } from '../../../lib/dbMonitor.js';

// Tracks all agent-generated outputs: middleware docs (TLDR, task lists),
// background findings, and file writes. One document per action.
const agentActionSchema = new mongoose.Schema(
  {
    agentId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Agent',
      required: true,
      index: true
    },
    // type drives how the action is displayed/filtered
    type: {
      type: String,
      enum: ['tldr', 'task_list', 'background', 'file_write', 'image', 'finding'],
      required: true
    },
    title: {
      type: String,
      default: ''
    },
    content: {
      type: String,
      required: true
    },
    // Extra context: { tool, args } for tool actions; { filename } for file_write etc.
    metadata: {
      type: mongoose.Schema.Types.Mixed,
      default: {}
    },
    tokens: {
      type: Number,
      default: 0
    },
    status: {
      type: String,
      enum: ['complete', 'error'],
      default: 'complete'
    },
    // True for actions generated by researcher/vibecoder pre-processing middleware.
    // Allows digest and action feeds to filter or label these separately.
    fromMiddleware: {
      type: Boolean,
      default: false
    }
  },
  {
    timestamps: true,
    collection: 'agent_actions'
  }
);

// Auto-expire background actions after 30 days; keep tldr/task_list/image/file_write indefinitely
agentActionSchema.index({ createdAt: 1 }, { expireAfterSeconds: 60 * 60 * 24 * 30, partialFilterExpression: { type: 'background' } });

// Static: latest N actions across all agents (findings view)
agentActionSchema.statics.getFindings = function(limit = 100) {
  return this.find({})
    .populate('agentId', 'name role')
    .sort({ createdAt: -1 })
    .limit(limit);
};

// ── DB Monitor hooks ──────────────────────────────────────────────────────────
agentActionSchema.post('save', function(doc) {
  trackDb('write', 'agent_actions', doc.agentId?.toString(), doc.type);
});
agentActionSchema.post('findOne', function(doc) {
  if (doc) trackDb('read', 'agent_actions', doc.agentId?.toString());
});
agentActionSchema.post('find', function(docs) {
  if (docs?.length) trackDb('read', 'agent_actions', null, `${docs.length} docs`);
});
agentActionSchema.post('deleteOne', function() {
  trackDb('write', 'agent_actions', null, 'delete');
});
agentActionSchema.post('deleteMany', function() {
  trackDb('write', 'agent_actions', null, 'deleteMany');
});

const AgentAction = mongoose.model('AgentAction', agentActionSchema);

export default AgentAction;
